model:
  backbone:
    name: convnext_tiny
    path: model/convnext_tiny.pth
  embedder:
    name: swin_tiny_patch4_window7_224
    path: model/swin_tiny_patch4_window7_224.pth
  latent_dims: 12544

batch_size: 32
epoch: 10
learning_rate: 0.0001
weight_decay: 0.0001
num_classes: 2
img_size: 224
min_val_loss: 10000
